language: node_js
node_js:
    - "8"
branches:
  only:
    - develop
    - master
script: node_modules/karma/bin/karma start karma.conf.js --single-run
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install

# before_install:
#   - export CHROME_BIN=chromium-browser
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start

# before_script:
#   - npm install -g bower
#   - npm install -g gulp
#   - npm install phantomjs
#   - npm install -g karma
#   - bower install
#   - gulp build
#   - gulp style
